---
abstract: ~
author:
  - 'Calle Dybedahl <calle@init.se>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Zonemaster-CLI
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Getopt::Long::Descriptive: 0
  JSON::XS: 0
  Locale::TextDomain: 0
  MooseX::Getopt: 0
  Net::LDNS: 0.65
  Text::Reflow: 0
  Zonemaster: 0.0.4
  perl: 5.14.2
resources:
  bugtracker: https://github.com/dotse/zonemaster/issues
  license: http://www.opensource.org/licenses/BSD-3-Clause
  repository: git@github.com:dotse/zonemaster.git
version: v0.1.2
